### PR TITLE
Feature: doctest options.

### PR DESCRIPTION
**Pull request by kindaro**
This should solve #20.

### CODE REVIEW

**Comment by kindaro** [comment]
I have no idea why it does not build [on Travis](https://travis-ci.org/karun012/doctest-discover/builds/345849396).

**Comment by karun012** [comment]
I haven't been able to get it to work on Travis using Stack. Still looking
into it.

**Comment by kindaro** [comment]
Can I expect this to be merged?

**Comment by karun012** [comment]
Yes, I will merge it. Once I get the build going on travis, it will be
easier to release new versions. I'll get to it over the weekend.

**Pull request merged**
