### PR TITLE
Recursively find modules, fix "-i/"

### LINKED ISSUE #9: Doesn't seem to work
Apologies in advance if I'm missing something, but I can't seem to get this library to find my source files.

```console
% ls src/**/*.hs
src/Data/Text/Escaped.hs
% stack exec doctest-discover "" "" /dev/stdout
module Main where
import Test.DocTest
main :: IO ()
main = doctest ["-i/src"]
```

I expected such an invocation to generate this:

```hs
module Main where
import Test.DocTest
main :: IO ()
main = doctest ["-isrc", "src/Data/Text/Escaped.hs"]
```

It's unclear to me why `-i` gets an absolute of `/src` rather than the relative `src`. I can get `doctest` to work with or without that option being correct (as long as I provide the `.hs` files), but that might explain why doctest-discover isn't finding source files (i.e. maybe it's looking for `/src/**/*.hs`).

### PR DESCRIPTION
**Pull request by pbrisbin**
See individual commit messages. Fixes #9 and #10.

Note: I threw in an update to the stack resolver just so I didn't have to wait
for everything to compile when I began working on this. Let me know if you want
me to back that out.

### CODE REVIEW

**Comment by karun012** [comment]
The stack resolver change is fine :-)

I'll merge your PR over the weekend. I haven't had any time to maintain
doctest-discover.

**Comment by pbrisbin** [comment]
Awesome thanks.

I'd be interested in taking over as maintainer if you're open to it. I'm also down to just help out, with you staying the main owner and gate-keeper -- I'd just want some freedom to get the project in line with my own style and conventions though, if that's OK. Let me know.

**Comment by karun012** [comment]
Absolutely. We can work something out.

**Comment by karun012** [comment]
Just getting back from vacation. Will merge your PR. Sorry for the delay.

**Pull request merged**
